name: deploy_my_model
description: Deploy the model
inputs:
  - {name: project_id, type: String, description: ''}
  - {name: model, type: Model, description: ''}
  - {name: serving_container_image_uri, type: String, description: ''}
  - {name: endpoint_machine_type, type: String, description: ''}
  - {name: endpoint_model_name, type: String, description: ''}
outputs:
  - {name: vertex_endpoint_uri, type: String, description: ''}
  - {name: vertex_model_uri, type: String, description: ''}
implementation:
  container:
    image: gcr.io/OWN_GCP_PROJECT_ID/sample_deploy
    command: [python3, src/main.py]
    args: [
      --project-id, {inputValue: project_id},
      --model, {inputPath: model},
      --serving-container-image-uri, {inputValue: serving_container_image_uri},
      --endpoint-machine-type, {inputValue: endpoint_machine_type},
      --endpoint-model-name, {inputValue: endpoint_model_name},
      
      --vertex-endpoint-uri, {outputPath: vertex_endpoint_uri},
      --vertex-model-uri, {outputPath: vertex_model_uri},
    ]